(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "evil")
(depends-on "coffee-mode")
(depends-on "slime" :git "https://github.com/slime/slime")
(depends-on "popwin" :git "https://github.com/m2ym/popwin-el")
(depends-on "js2-mode" :git "https://github.com/mooz/js2-mode")
(depends-on "paredit")
(depends-on "evil-paredit")
(depends-on "emmet-mode")
(depends-on "smartparens")
(depends-on "emacs-async" :git "https://github.com/jwiegley/emacs-async.git")
(depends-on "helm")
(depends-on "undo-tree")
(depends-on "undohist")
(depends-on "scss-mode")
(depends-on "jsx-mode")
(depends-on "yaml-mode")
(depends-on "js-comint" :git "https://github.com/redguardtoo/js-comint")
(depends-on "quickrun")
(depends-on "flycheck-pos-tip")
(depends-on "evil-dvorak")
(depends-on "twittering-mode")
(depends-on "rust-mode")
(depends-on "flycheck-rust")
(depends-on "go-mode")
(depends-on "go-autocomplete")
(depends-on "go-eldoc")
(depends-on "markdown-mode")
(depends-on "livedown" :git "https://github.com/shime/emacs-livedown")
(depends-on "alchemist")
(depends-on "perl-completion")
(depends-on "haskell-mode")
(depends-on "ruby-electric")
(depends-on "ruby-block")
(depends-on "rubocop")
(depends-on "tuareg")
(depends-on "crystal-mode" :git "https://github.com/jpellerin/emacs-crystal-mode")
